apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr 
      image: 10507/surajimages:dockerdemoproj
      ports:
        - containerPort: 8082